# ApiConfig for dev environment #
api:
  version: "v1"

# server #
server:
  error:
    path: /error
  port: 8087
  servlet:
    contextPath: /bitcoin-prices-api

# logger #
logging:
  level:
    org:
      springframework:
        data: WARN
        web: WARN
    net:
      marco27:
        api: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

spring:
  datasource:
    url: jdbc:sqlite:/Users/marcoguastalli/opt/sqlite/prices.sqlite
  jpa:
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    show-sql: true
# create – Hibernate first drops existing tables, then creates new tables
# update – the object model created based on the mappings is compared with the existing schema, and then Hibernate updates the schema according to the diff.
#          It never deletes the existing tables or columns even if they are no more required by the application
# create-drop – similar to create, with the addition that Hibernate will drop the database after all operations are completed.
#               Typically used for unit testing
# validate – Hibernate only validates whether the tables and columns exist, otherwise it throws an exception
#  none – this value effectively turns off the DDL generation
